site_name: "Gait Recording - Docs"
repo_url: https://jburoko@dev.azure.com/jburoko/CP-Detector/_git/OakDVideoRecorder
repo_name: "Azure DevOps"
site_description: "System to record and process Gait Cycles"
site_author: "John Uroko john.uroko@cloudflight.io"

nav:
  - Overview: index.md
  - Instructions: instructions/
  - Code Reference: reference/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
    - content.code.annotation
    - toc.follow

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

plugins:
  - search
  - section-index
  - glightbox
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_bases: true
            show_source: true
            members_order: alphabetical
