site_name: "Gait Recording - Docs"
repo_url: https://jburoko@dev.azure.com/jburoko/CP-Detector/_git/OakDVideoRecorder
repo_name: "Azure DevOps"
site_description: "System to record and process Gait Cycles"
site_author: "John Uroko john.uroko@cloudflight.io"

nav:
  - Home: index.md
  - Instructions: instructions/
  - Code Reference: reference/

theme:
  name: material
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
    - content.code.annotation
    - toc.follow

plugins:
  - search
  - section-index
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_bases: true
            show_source: true
            members_order: alphabetical
